/***************************************************************************
***
***     Copyright (C) 2022-2023 IntelliCAD Technology Consortium. All Rights Reserved.
***
***     Use of the information contained herein, in part or in whole,
***     in/as source code and/or in/as object code, in any way by anyone
***     other than authorized employees of The IntelliCAD Technology Consortium,
***     or by anyone to whom The IntelliCAD Technology Consortium  has not
***     granted use is illegal.
***
***     Description:
***
*****************************************************************************/
#pragma once

#include "acadstrc.h"
#include "acdb.h"

typedef Acad::ErrorStatus ErrorStatus;

typedef AcDb::OpenMode OpenMode;
typedef AcDb::OsnapMode OsnapMode;
typedef AcDb::CoordAxis CoordAxis;
typedef AcDb::CoordSystem CoordSystem;
typedef AcDb::Intersect Intersect;
typedef AcDb::Visibility Visibility;
typedef AcDb::SaveType SaveType;
typedef AcDb::DxfCode DxfCode;
typedef AcDb::DwgDataType DwgDataType;
typedef AcDb::TextHorzMode TextHorzMode;
typedef AcDb::TextVertMode TextVertMode;
typedef AcDb::LineSpacingStyle LineSpacingStyle;
typedef AcDb::Planarity Planarity;
typedef AcDb::PointIndex PointIndex;
typedef AcDb::EdgeIndex EdgeIndex;
typedef AcDb::Poly2dType Poly2dType;
typedef AcDb::Poly3dType Poly3dType;
typedef AcDb::PolyMeshType PolyMeshType;
typedef AcDb::Vertex2dType Vertex2dType;
typedef AcDb::Vertex3dType Vertex3dType;
typedef AcDb::SpaceValueType SpaceValueType;
typedef AcDb::BoolOperType BoolOperType;
typedef AcDb::SubentType SubentType;
typedef AcDb::GeomId GeomId;
typedef AcDb::GeomType GeomType;
typedef AcDb::OrthographicView OrthographicView;

const Acad::ErrorStatus eAlreadyHasRepresentation = Acad::ErrorStatus::eAlreadyHasRepresentation;
const Acad::ErrorStatus eAlreadyInDb = Acad::ErrorStatus::eAlreadyInDb;
const Acad::ErrorStatus eAlreadyInGroup = Acad::ErrorStatus::eAlreadyInGroup;
const Acad::ErrorStatus eAmbiguousInput = Acad::ErrorStatus::eAmbiguousInput;
const Acad::ErrorStatus eAmbiguousOutput = Acad::ErrorStatus::eAmbiguousOutput;
const Acad::ErrorStatus eAnonymousEntry = Acad::ErrorStatus::eAnonymousEntry;
const Acad::ErrorStatus eAtMaxReaders = Acad::ErrorStatus::eAtMaxReaders;
const Acad::ErrorStatus eBackgroundPlotInProgress = Acad::ErrorStatus::eBackgroundPlotInProgress;
const Acad::ErrorStatus eBadColor = Acad::ErrorStatus::eBadColor;
const Acad::ErrorStatus eBadColorIndex = Acad::ErrorStatus::eBadColorIndex;
const Acad::ErrorStatus eBadDxfFile = Acad::ErrorStatus::eBadDxfFile;
const Acad::ErrorStatus eBadDxfSequence = Acad::ErrorStatus::eBadDxfSequence;
const Acad::ErrorStatus eBadLayerName = Acad::ErrorStatus::eBadLayerName;
const Acad::ErrorStatus eBadLinetypeName = Acad::ErrorStatus::eBadLinetypeName;
const Acad::ErrorStatus eBadLinetypeScale = Acad::ErrorStatus::eBadLinetypeScale;
const Acad::ErrorStatus eBadlyNestedAppData = Acad::ErrorStatus::eBadlyNestedAppData;
const Acad::ErrorStatus eBadMaterialName = Acad::ErrorStatus::eBadMaterialName;
const Acad::ErrorStatus eBadPaperspaceView = Acad::ErrorStatus::eBadPaperspaceView;
const Acad::ErrorStatus eBadPlotStyleName = Acad::ErrorStatus::eBadPlotStyleName;
const Acad::ErrorStatus eBadPlotStyleNameHandle = Acad::ErrorStatus::eBadPlotStyleNameHandle;
const Acad::ErrorStatus eBadPlotStyleType = Acad::ErrorStatus::eBadPlotStyleType;
const Acad::ErrorStatus eBadUCS = Acad::ErrorStatus::eBadUCS;
const Acad::ErrorStatus eBadVisibilityValue = Acad::ErrorStatus::eBadVisibilityValue;
const Acad::ErrorStatus eBinaryDataSizeExceeded = Acad::ErrorStatus::eBinaryDataSizeExceeded;
const Acad::ErrorStatus eBlockDefInEntitySection = Acad::ErrorStatus::eBlockDefInEntitySection;
const Acad::ErrorStatus eBrokenHandle = Acad::ErrorStatus::eBrokenHandle;
const Acad::ErrorStatus eBufferTooSmall = Acad::ErrorStatus::eBufferTooSmall;
const Acad::ErrorStatus eCannotBeErasedByCaller = Acad::ErrorStatus::eCannotBeErasedByCaller;
const Acad::ErrorStatus eCannotChangeActiveViewport = Acad::ErrorStatus::eCannotChangeActiveViewport;
const Acad::ErrorStatus eCannotChangeColumnType = Acad::ErrorStatus::eCannotChangeColumnType;
const Acad::ErrorStatus eCannotExplodeEntity = Acad::ErrorStatus::eCannotExplodeEntity;
const Acad::ErrorStatus eCannotNestBlockDefs = Acad::ErrorStatus::eCannotNestBlockDefs;
const Acad::ErrorStatus eCannotPlotToFile = Acad::ErrorStatus::eCannotPlotToFile;
const Acad::ErrorStatus eCannotRestoreFromAcisFile = Acad::ErrorStatus::eCannotRestoreFromAcisFile;
const Acad::ErrorStatus eCannotScaleNonUniformly = Acad::ErrorStatus::eCannotScaleNonUniformly;
const Acad::ErrorStatus eCantOpenFile = Acad::ErrorStatus::eCantOpenFile;
const Acad::ErrorStatus eChangedAgainstAssociativity = Acad::ErrorStatus::eChangedAgainstAssociativity;
const Acad::ErrorStatus eCloseModifyAborted = Acad::ErrorStatus::eCloseModifyAborted;
const Acad::ErrorStatus eClosePartialFailure = Acad::ErrorStatus::eClosePartialFailure;
const Acad::ErrorStatus eCloseWasNotifying = Acad::ErrorStatus::eCloseWasNotifying;
const Acad::ErrorStatus eCommandWasInProgress = Acad::ErrorStatus::eCommandWasInProgress;
const Acad::ErrorStatus eContainerNotEmpty = Acad::ErrorStatus::eContainerNotEmpty;
const Acad::ErrorStatus eCustomSizeNotPossible = Acad::ErrorStatus::eCustomSizeNotPossible;
const Acad::ErrorStatus eCyclicDependency = Acad::ErrorStatus::eCyclicDependency;
const Acad::ErrorStatus eDatabaseObjectsOpen = Acad::ErrorStatus::eDatabaseObjectsOpen;
const Acad::ErrorStatus eDegenerateGeometry = Acad::ErrorStatus::eDegenerateGeometry;
const Acad::ErrorStatus eDeletedEntry = Acad::ErrorStatus::eDeletedEntry;
const Acad::ErrorStatus eDeleteEntity = Acad::ErrorStatus::eDeleteEntity;
const Acad::ErrorStatus eDependentOnObjectErased = Acad::ErrorStatus::eDependentOnObjectErased;
const Acad::ErrorStatus eDeviceNotFound = Acad::ErrorStatus::eDeviceNotFound;
const Acad::ErrorStatus eDocumentSwitchDisabled = Acad::ErrorStatus::eDocumentSwitchDisabled;
const Acad::ErrorStatus eDuplicateBlockDefinition = Acad::ErrorStatus::eDuplicateBlockDefinition;
const Acad::ErrorStatus eDuplicateBlockName = Acad::ErrorStatus::eDuplicateBlockName;
const Acad::ErrorStatus eDuplicateDxfField = Acad::ErrorStatus::eDuplicateDxfField;
const Acad::ErrorStatus eDuplicateIndex = Acad::ErrorStatus::eDuplicateIndex;
const Acad::ErrorStatus eDuplicateKey = Acad::ErrorStatus::eDuplicateKey;
const Acad::ErrorStatus eDuplicateLayerName = Acad::ErrorStatus::eDuplicateLayerName;
const Acad::ErrorStatus eDuplicateRecordName = Acad::ErrorStatus::eDuplicateRecordName;
const Acad::ErrorStatus eDwgCRCDoesNotMatch = Acad::ErrorStatus::eDwgCRCDoesNotMatch;
const Acad::ErrorStatus eDwgNeedsAFullSave = Acad::ErrorStatus::eDwgNeedsAFullSave;
const Acad::ErrorStatus eDwgNeedsRecovery = Acad::ErrorStatus::eDwgNeedsRecovery;
const Acad::ErrorStatus eDwgNotRecoverable = Acad::ErrorStatus::eDwgNotRecoverable;
const Acad::ErrorStatus eDwgObjectImproperlyRead = Acad::ErrorStatus::eDwgObjectImproperlyRead;
const Acad::ErrorStatus eDwgRecoveredOK = Acad::ErrorStatus::eDwgRecoveredOK;
const Acad::ErrorStatus eDwgSentinelDoesNotMatch = Acad::ErrorStatus::eDwgSentinelDoesNotMatch;
const Acad::ErrorStatus eDwgShareDemandLoad = Acad::ErrorStatus::eDwgShareDemandLoad;
const Acad::ErrorStatus eDwgShareReadAccess = Acad::ErrorStatus::eDwgShareReadAccess;
const Acad::ErrorStatus eDwgShareWriteAccess = Acad::ErrorStatus::eDwgShareWriteAccess;
const Acad::ErrorStatus eDwkLockFileFound = Acad::ErrorStatus::eDwkLockFileFound;
const Acad::ErrorStatus eDxbPartiallyRead = Acad::ErrorStatus::eDxbPartiallyRead;
const Acad::ErrorStatus eDxbReadAborted = Acad::ErrorStatus::eDxbReadAborted;
const Acad::ErrorStatus eDxfPartiallyRead = Acad::ErrorStatus::eDxfPartiallyRead;
const Acad::ErrorStatus eDxfReadAborted = Acad::ErrorStatus::eDxfReadAborted;
const Acad::ErrorStatus eEmbeddedIntersections = Acad::ErrorStatus::eEmbeddedIntersections;
const Acad::ErrorStatus eEndOfFile = Acad::ErrorStatus::eEndOfFile;
const Acad::ErrorStatus eEndOfObject = Acad::ErrorStatus::eEndOfObject;
const Acad::ErrorStatus eEntityInInactiveLayout = Acad::ErrorStatus::eEntityInInactiveLayout;
const Acad::ErrorStatus eExcessiveItemCount = Acad::ErrorStatus::eExcessiveItemCount;
const Acad::ErrorStatus eExplodeBeforeTransform = Acad::ErrorStatus::eExplodeBeforeTransform;
const Acad::ErrorStatus eFailedToBlend = Acad::ErrorStatus::eFailedToBlend;
const Acad::ErrorStatus eFailedToEvaluate = Acad::ErrorStatus::eFailedToEvaluate;
const Acad::ErrorStatus eFailedToEvaluateDependents = Acad::ErrorStatus::eFailedToEvaluateDependents;
const Acad::ErrorStatus eFailedToSetEdgeChamfers = Acad::ErrorStatus::eFailedToSetEdgeChamfers;
const Acad::ErrorStatus eFailedToSetEdgeRounds = Acad::ErrorStatus::eFailedToSetEdgeRounds;
const Acad::ErrorStatus eFailedToSetVertexRounds = Acad::ErrorStatus::eFailedToSetVertexRounds;
const Acad::ErrorStatus eFileAccessErr = Acad::ErrorStatus::eFileAccessErr;
const Acad::ErrorStatus eFileExists = Acad::ErrorStatus::eFileExists;
const Acad::ErrorStatus eFileInternalErr = Acad::ErrorStatus::eFileInternalErr;
const Acad::ErrorStatus eFileLockedByACAD = Acad::ErrorStatus::eFileLockedByACAD;
const Acad::ErrorStatus eFileNotFound = Acad::ErrorStatus::eFileNotFound;
const Acad::ErrorStatus eFilerError = Acad::ErrorStatus::eFilerError;
const Acad::ErrorStatus eFileSystemErr = Acad::ErrorStatus::eFileSystemErr;
const Acad::ErrorStatus eFixedAllErrors = Acad::ErrorStatus::eFixedAllErrors;
const Acad::ErrorStatus eFSMError = Acad::ErrorStatus::eFSMError;
const Acad::ErrorStatus eGeneralModelingFailure = Acad::ErrorStatus::eGeneralModelingFailure;
const Acad::ErrorStatus eGraphContainsProxies = Acad::ErrorStatus::eGraphContainsProxies;
const Acad::ErrorStatus eGraphCyclesFound = Acad::ErrorStatus::eGraphCyclesFound;
const Acad::ErrorStatus eGraphEdgeAlreadyExists = Acad::ErrorStatus::eGraphEdgeAlreadyExists;
const Acad::ErrorStatus eGraphEdgeNotFound = Acad::ErrorStatus::eGraphEdgeNotFound;
const Acad::ErrorStatus eGraphicsNotGenerated = Acad::ErrorStatus::eGraphicsNotGenerated;
const Acad::ErrorStatus eGraphNodeAlreadyExists = Acad::ErrorStatus::eGraphNodeAlreadyExists;
const Acad::ErrorStatus eGraphNodeNotFound = Acad::ErrorStatus::eGraphNodeNotFound;
const Acad::ErrorStatus eGuidNoAddress = Acad::ErrorStatus::eGuidNoAddress;
const Acad::ErrorStatus eHadMultipleReaders = Acad::ErrorStatus::eHadMultipleReaders;
const Acad::ErrorStatus eHandleExists = Acad::ErrorStatus::eHandleExists;
const Acad::ErrorStatus eHandleInUse = Acad::ErrorStatus::eHandleInUse;
const Acad::ErrorStatus eHatchTooDense = Acad::ErrorStatus::eHatchTooDense;
const Acad::ErrorStatus eIgnoredLinetypeRedef = Acad::ErrorStatus::eIgnoredLinetypeRedef;
const Acad::ErrorStatus eIllegalEntityType = Acad::ErrorStatus::eIllegalEntityType;
const Acad::ErrorStatus eIllegalReplacement = Acad::ErrorStatus::eIllegalReplacement;
const Acad::ErrorStatus eIncompatiblePlotSettings = Acad::ErrorStatus::eIncompatiblePlotSettings;
const Acad::ErrorStatus eIncompleteBlockDefinition = Acad::ErrorStatus::eIncompleteBlockDefinition;
const Acad::ErrorStatus eIncompleteComplexObject = Acad::ErrorStatus::eIncompleteComplexObject;
const Acad::ErrorStatus eInconsistentConstraint = Acad::ErrorStatus::eInconsistentConstraint;
const Acad::ErrorStatus eInProcessOfCommitting = Acad::ErrorStatus::eInProcessOfCommitting;
const Acad::ErrorStatus eInvalidAdsName = Acad::ErrorStatus::eInvalidAdsName;
const Acad::ErrorStatus eInvalidAxis = Acad::ErrorStatus::eInvalidAxis;
const Acad::ErrorStatus eInvalidBlockName = Acad::ErrorStatus::eInvalidBlockName;
const Acad::ErrorStatus eInvalidContext = Acad::ErrorStatus::eInvalidContext;
const Acad::ErrorStatus eInvalidDimStyle = Acad::ErrorStatus::eInvalidDimStyle;
const Acad::ErrorStatus eInvalidDwgVersion = Acad::ErrorStatus::eInvalidDwgVersion;
const Acad::ErrorStatus eInvalidDxf2dPoint = Acad::ErrorStatus::eInvalidDxf2dPoint;
const Acad::ErrorStatus eInvalidDxf3dPoint = Acad::ErrorStatus::eInvalidDxf3dPoint;
const Acad::ErrorStatus eInvalidDxfCode = Acad::ErrorStatus::eInvalidDxfCode;
const Acad::ErrorStatus eInvalidDxfSectionName = Acad::ErrorStatus::eInvalidDxfSectionName;
const Acad::ErrorStatus eInvalidEngineState = Acad::ErrorStatus::eInvalidEngineState;
const Acad::ErrorStatus eInvalidExpression = Acad::ErrorStatus::eInvalidExpression;
const Acad::ErrorStatus eInvalidExtents = Acad::ErrorStatus::eInvalidExtents;
const Acad::ErrorStatus eInvalidFaceVertexIndex = Acad::ErrorStatus::eInvalidFaceVertexIndex;
const Acad::ErrorStatus eInvalidFileExtension = Acad::ErrorStatus::eInvalidFileExtension;
const Acad::ErrorStatus eInvalidFix = Acad::ErrorStatus::eInvalidFix;
const Acad::ErrorStatus eInvalidIdMap = Acad::ErrorStatus::eInvalidIdMap;
const Acad::ErrorStatus eInvalidIndex = Acad::ErrorStatus::eInvalidIndex;
const Acad::ErrorStatus eInvalidInput = Acad::ErrorStatus::eInvalidInput;
const Acad::ErrorStatus eInvalidKey = Acad::ErrorStatus::eInvalidKey;
const Acad::ErrorStatus eInvalidLayer = Acad::ErrorStatus::eInvalidLayer;
const Acad::ErrorStatus eInvalidMeshVertexIndex = Acad::ErrorStatus::eInvalidMeshVertexIndex;
const Acad::ErrorStatus eInvalidObjectId = Acad::ErrorStatus::eInvalidObjectId;
const Acad::ErrorStatus eInvalidOffset = Acad::ErrorStatus::eInvalidOffset;
const Acad::ErrorStatus eInvalidOpenState = Acad::ErrorStatus::eInvalidOpenState;
const Acad::ErrorStatus eInvalidOwnerObject = Acad::ErrorStatus::eInvalidOwnerObject;
const Acad::ErrorStatus eInvalidParameterName = Acad::ErrorStatus::eInvalidParameterName;
const Acad::ErrorStatus eInvalidPlotArea = Acad::ErrorStatus::eInvalidPlotArea;
const Acad::ErrorStatus eInvalidPlotInfo = Acad::ErrorStatus::eInvalidPlotInfo;
const Acad::ErrorStatus eInvalidProfileName = Acad::ErrorStatus::eInvalidProfileName;
const Acad::ErrorStatus eInvalidResBuf = Acad::ErrorStatus::eInvalidResBuf;
const Acad::ErrorStatus eInvalidStyle = Acad::ErrorStatus::eInvalidStyle;
const Acad::ErrorStatus eInvalidSymbolTableName = Acad::ErrorStatus::eInvalidSymbolTableName;
const Acad::ErrorStatus eInvalidSymTableFlag = Acad::ErrorStatus::eInvalidSymTableFlag;
const Acad::ErrorStatus eInvalidTextStyle = Acad::ErrorStatus::eInvalidTextStyle;
const Acad::ErrorStatus eInvalidView = Acad::ErrorStatus::eInvalidView;
const Acad::ErrorStatus eInvalidWindowArea = Acad::ErrorStatus::eInvalidWindowArea;
const Acad::ErrorStatus eInvalidXrefObjectId = Acad::ErrorStatus::eInvalidXrefObjectId;
const Acad::ErrorStatus eIsAnEntity = Acad::ErrorStatus::eIsAnEntity;
const Acad::ErrorStatus eIsReading = Acad::ErrorStatus::eIsReading;
const Acad::ErrorStatus eIsWriteProtected = Acad::ErrorStatus::eIsWriteProtected;
const Acad::ErrorStatus eIsWriting = Acad::ErrorStatus::eIsWriting;
const Acad::ErrorStatus eIsXRefObject = Acad::ErrorStatus::eIsXRefObject;
const Acad::ErrorStatus eIteratorDone = Acad::ErrorStatus::eIteratorDone;
const Acad::ErrorStatus eKeyNotFound = Acad::ErrorStatus::eKeyNotFound;
const Acad::ErrorStatus eLayerGroupCodeMissing = Acad::ErrorStatus::eLayerGroupCodeMissing;
const Acad::ErrorStatus eLayoutNotCurrent = Acad::ErrorStatus::eLayoutNotCurrent;
const Acad::ErrorStatus eLeftErrorsUnfixed = Acad::ErrorStatus::eLeftErrorsUnfixed;
const Acad::ErrorStatus eLISPActive = Acad::ErrorStatus::eLISPActive;
const Acad::ErrorStatus eLoadFailed = Acad::ErrorStatus::eLoadFailed;
const Acad::ErrorStatus eLockChangeInProgress = Acad::ErrorStatus::eLockChangeInProgress;
const Acad::ErrorStatus eLockConflict = Acad::ErrorStatus::eLockConflict;
const Acad::ErrorStatus eLockViolation = Acad::ErrorStatus::eLockViolation;
const Acad::ErrorStatus eLongTransReferenceError = Acad::ErrorStatus::eLongTransReferenceError;
const Acad::ErrorStatus eMaxLayouts = Acad::ErrorStatus::eMaxLayouts;
const Acad::ErrorStatus eMissingBlockName = Acad::ErrorStatus::eMissingBlockName;
const Acad::ErrorStatus eMissingDxfField = Acad::ErrorStatus::eMissingDxfField;
const Acad::ErrorStatus eMissingDxfSection = Acad::ErrorStatus::eMissingDxfSection;
const Acad::ErrorStatus eMissingSymbolTable = Acad::ErrorStatus::eMissingSymbolTable;
const Acad::ErrorStatus eMissingSymbolTableRec = Acad::ErrorStatus::eMissingSymbolTableRec;
const Acad::ErrorStatus eModifyingAssociativeEntity = Acad::ErrorStatus::eModifyingAssociativeEntity;
const Acad::ErrorStatus eModifyingDimensionWithExpression = Acad::ErrorStatus::eModifyingDimensionWithExpression;
const Acad::ErrorStatus eMustFirstAddBlockToDb = Acad::ErrorStatus::eMustFirstAddBlockToDb;
const Acad::ErrorStatus eMustOpenThruOwner = Acad::ErrorStatus::eMustOpenThruOwner;
const Acad::ErrorStatus eMustPlotToFile = Acad::ErrorStatus::eMustPlotToFile;
const Acad::ErrorStatus eNegativeValueNotAllowed = Acad::ErrorStatus::eNegativeValueNotAllowed;
const Acad::ErrorStatus eNoActiveTransactions = Acad::ErrorStatus::eNoActiveTransactions;
const Acad::ErrorStatus eNoBlockBegin = Acad::ErrorStatus::eNoBlockBegin;
const Acad::ErrorStatus eNoClassId = Acad::ErrorStatus::eNoClassId;
const Acad::ErrorStatus eNoConnectedBlendSet = Acad::ErrorStatus::eNoConnectedBlendSet;
const Acad::ErrorStatus eNoCurrentConfig = Acad::ErrorStatus::eNoCurrentConfig;
const Acad::ErrorStatus eNoDatabase = Acad::ErrorStatus::eNoDatabase;
const Acad::ErrorStatus eNoDocument = Acad::ErrorStatus::eNoDocument;
const Acad::ErrorStatus eNoErrorHandler = Acad::ErrorStatus::eNoErrorHandler;
const Acad::ErrorStatus eNoFileName = Acad::ErrorStatus::eNoFileName;
const Acad::ErrorStatus eNoInputFiler = Acad::ErrorStatus::eNoInputFiler;
const Acad::ErrorStatus eNoInputPath = Acad::ErrorStatus::eNoInputPath;
const Acad::ErrorStatus eNoInternalSpace = Acad::ErrorStatus::eNoInternalSpace;
const Acad::ErrorStatus eNoIntersections = Acad::ErrorStatus::eNoIntersections;
const Acad::ErrorStatus eNoLabelBlock = Acad::ErrorStatus::eNoLabelBlock;
const Acad::ErrorStatus eNoLayout = Acad::ErrorStatus::eNoLayout;
const Acad::ErrorStatus eNoMatchingMedia = Acad::ErrorStatus::eNoMatchingMedia;
const Acad::ErrorStatus eNonCoplanarGeometry = Acad::ErrorStatus::eNonCoplanarGeometry;
const Acad::ErrorStatus eNonePlotDevice = Acad::ErrorStatus::eNonePlotDevice;
const Acad::ErrorStatus eNoNodeActive = Acad::ErrorStatus::eNoNodeActive;
const Acad::ErrorStatus eNonPlanarEntity = Acad::ErrorStatus::eNonPlanarEntity;
const Acad::ErrorStatus eNoPlotStyleTranslationTable = Acad::ErrorStatus::eNoPlotStyleTranslationTable;
const Acad::ErrorStatus eNoRepresentation = Acad::ErrorStatus::eNoRepresentation;
const Acad::ErrorStatus eNotAnEntity = Acad::ErrorStatus::eNotAnEntity;
const Acad::ErrorStatus eNotApplicable = Acad::ErrorStatus::eNotApplicable;
const Acad::ErrorStatus eNotAssociative = Acad::ErrorStatus::eNotAssociative;
const Acad::ErrorStatus eNotConnected = Acad::ErrorStatus::eNotConnected;
const Acad::ErrorStatus eNotCurrentDatabase = Acad::ErrorStatus::eNotCurrentDatabase;
const Acad::ErrorStatus eNotDxfHeaderGroupCode = Acad::ErrorStatus::eNotDxfHeaderGroupCode;
const Acad::ErrorStatus eNotFromThisDocument = Acad::ErrorStatus::eNotFromThisDocument;
const Acad::ErrorStatus eNotG1Continuous = Acad::ErrorStatus::eNotG1Continuous;
const Acad::ErrorStatus eNoThumbnailBitmap = Acad::ErrorStatus::eNoThumbnailBitmap;
const Acad::ErrorStatus eNotImplementedYet = Acad::ErrorStatus::eNotImplementedYet;
const Acad::ErrorStatus eNotInBlock = Acad::ErrorStatus::eNotInBlock;
const Acad::ErrorStatus eNotInDatabase = Acad::ErrorStatus::eNotInDatabase;
const Acad::ErrorStatus eNotInGroup = Acad::ErrorStatus::eNotInGroup;
const Acad::ErrorStatus eNotInitializedYet = Acad::ErrorStatus::eNotInitializedYet;
const Acad::ErrorStatus eNotInPaperspace = Acad::ErrorStatus::eNotInPaperspace;
const Acad::ErrorStatus eNotNewlyCreated = Acad::ErrorStatus::eNotNewlyCreated;
const Acad::ErrorStatus eNotOnBoundary = Acad::ErrorStatus::eNotOnBoundary;
const Acad::ErrorStatus eNotOpenForRead = Acad::ErrorStatus::eNotOpenForRead;
const Acad::ErrorStatus eNotOpenForWrite = Acad::ErrorStatus::eNotOpenForWrite;
const Acad::ErrorStatus eNotThatKindOfClass = Acad::ErrorStatus::eNotThatKindOfClass;
const Acad::ErrorStatus eNotTopTransaction = Acad::ErrorStatus::eNotTopTransaction;
const Acad::ErrorStatus eNoViewAssociation = Acad::ErrorStatus::eNoViewAssociation;
const Acad::ErrorStatus eNoWorkSet = Acad::ErrorStatus::eNoWorkSet;
const Acad::ErrorStatus eNullBlockName = Acad::ErrorStatus::eNullBlockName;
const Acad::ErrorStatus eNullEntityPointer = Acad::ErrorStatus::eNullEntityPointer;
const Acad::ErrorStatus eNullExtents = Acad::ErrorStatus::eNullExtents;
const Acad::ErrorStatus eNullHandle = Acad::ErrorStatus::eNullHandle;
const Acad::ErrorStatus eNullIterator = Acad::ErrorStatus::eNullIterator;
const Acad::ErrorStatus eNullNodeId = Acad::ErrorStatus::eNullNodeId;
const Acad::ErrorStatus eNullObjectId = Acad::ErrorStatus::eNullObjectId;
const Acad::ErrorStatus eNullObjectPointer = Acad::ErrorStatus::eNullObjectPointer;
const Acad::ErrorStatus eNullPtr = Acad::ErrorStatus::eNullPtr;
const Acad::ErrorStatus eNumberOfCopiesNotSupported = Acad::ErrorStatus::eNumberOfCopiesNotSupported;
const Acad::ErrorStatus eObjectIsReferenced = Acad::ErrorStatus::eObjectIsReferenced;
const Acad::ErrorStatus eObjectToBeDeleted = Acad::ErrorStatus::eObjectToBeDeleted;
const Acad::ErrorStatus eOk = Acad::ErrorStatus::eOk;
const Acad::ErrorStatus eOnLockedLayer = Acad::ErrorStatus::eOnLockedLayer;
const Acad::ErrorStatus eOtherObjectsBusy = Acad::ErrorStatus::eOtherObjectsBusy;
const Acad::ErrorStatus eOutOfDisk = Acad::ErrorStatus::eOutOfDisk;
const Acad::ErrorStatus eOutOfMemory = Acad::ErrorStatus::eOutOfMemory;
const Acad::ErrorStatus eOutOfPagerMemory = Acad::ErrorStatus::eOutOfPagerMemory;
const Acad::ErrorStatus eOutOfRange = Acad::ErrorStatus::eOutOfRange;
const Acad::ErrorStatus eOverDefinedConstraint = Acad::ErrorStatus::eOverDefinedConstraint;
const Acad::ErrorStatus eOwnerNotInDatabase = Acad::ErrorStatus::eOwnerNotInDatabase;
const Acad::ErrorStatus eOwnerNotOpenForRead = Acad::ErrorStatus::eOwnerNotOpenForRead;
const Acad::ErrorStatus eOwnerNotOpenForWrite = Acad::ErrorStatus::eOwnerNotOpenForWrite;
const Acad::ErrorStatus eOwnerNotSet = Acad::ErrorStatus::eOwnerNotSet;
const Acad::ErrorStatus ePageCancelled = Acad::ErrorStatus::ePageCancelled;
const Acad::ErrorStatus ePagerError = Acad::ErrorStatus::ePagerError;
const Acad::ErrorStatus ePagerWriteError = Acad::ErrorStatus::ePagerWriteError;
const Acad::ErrorStatus ePermanentlyErased = Acad::ErrorStatus::ePermanentlyErased;
const Acad::ErrorStatus ePlotAlreadyStarted = Acad::ErrorStatus::ePlotAlreadyStarted;
const Acad::ErrorStatus ePlotCancelled = Acad::ErrorStatus::ePlotCancelled;
const Acad::ErrorStatus ePlotStyleInColorDependentMode = Acad::ErrorStatus::ePlotStyleInColorDependentMode;
const Acad::ErrorStatus ePointNotOnEntity = Acad::ErrorStatus::ePointNotOnEntity;
const Acad::ErrorStatus ePolyWidthLost = Acad::ErrorStatus::ePolyWidthLost;
const Acad::ErrorStatus eProfileDoesNotExist = Acad::ErrorStatus::eProfileDoesNotExist;
const Acad::ErrorStatus eProfileIsInUse = Acad::ErrorStatus::eProfileIsInUse;
const Acad::ErrorStatus eProperClassSeparatorExpected = Acad::ErrorStatus::eProperClassSeparatorExpected;
const Acad::ErrorStatus eRecordNotInTable = Acad::ErrorStatus::eRecordNotInTable;
const Acad::ErrorStatus eReferencedInEquation = Acad::ErrorStatus::eReferencedInEquation;
const Acad::ErrorStatus eRegappIdNotFound = Acad::ErrorStatus::eRegappIdNotFound;
const Acad::ErrorStatus eRegistryAccessError = Acad::ErrorStatus::eRegistryAccessError;
const Acad::ErrorStatus eRegistryCreateError = Acad::ErrorStatus::eRegistryCreateError;
const Acad::ErrorStatus eRepeatEntity = Acad::ErrorStatus::eRepeatEntity;
const Acad::ErrorStatus eRowsMustMatchColumns = Acad::ErrorStatus::eRowsMustMatchColumns;
const Acad::ErrorStatus eSelfIntersecting = Acad::ErrorStatus::eSelfIntersecting;
const Acad::ErrorStatus eSelfReference = Acad::ErrorStatus::eSelfReference;
const Acad::ErrorStatus eSingularPoint = Acad::ErrorStatus::eSingularPoint;
const Acad::ErrorStatus eSomeInputDataLeftUnread = Acad::ErrorStatus::eSomeInputDataLeftUnread;
const Acad::ErrorStatus eStringNotAllowedInExpression = Acad::ErrorStatus::eStringNotAllowedInExpression;
const Acad::ErrorStatus eStringTooLong = Acad::ErrorStatus::eStringTooLong;
const Acad::ErrorStatus eSubentitiesStillOpen = Acad::ErrorStatus::eSubentitiesStillOpen;
const Acad::ErrorStatus eSubSelectionSetEmpty = Acad::ErrorStatus::eSubSelectionSetEmpty;
const Acad::ErrorStatus eTargetDocNotQuiescent = Acad::ErrorStatus::eTargetDocNotQuiescent;
const Acad::ErrorStatus eTooFewLineTypeElements = Acad::ErrorStatus::eTooFewLineTypeElements;
const Acad::ErrorStatus eTooManyActiveCommands = Acad::ErrorStatus::eTooManyActiveCommands;
const Acad::ErrorStatus eTooManyLineTypeElements = Acad::ErrorStatus::eTooManyLineTypeElements;
const Acad::ErrorStatus eTransactionOpenWhileCommandEnded = Acad::ErrorStatus::eTransactionOpenWhileCommandEnded;
const Acad::ErrorStatus eUnableToGetLabelBlock = Acad::ErrorStatus::eUnableToGetLabelBlock;
const Acad::ErrorStatus eUnableToGetViewAssociation = Acad::ErrorStatus::eUnableToGetViewAssociation;
const Acad::ErrorStatus eUnableToRemoveAssociation = Acad::ErrorStatus::eUnableToRemoveAssociation;
const Acad::ErrorStatus eUnableToSetLabelBlock = Acad::ErrorStatus::eUnableToSetLabelBlock;
const Acad::ErrorStatus eUnableToSetViewAssociation = Acad::ErrorStatus::eUnableToSetViewAssociation;
const Acad::ErrorStatus eUnableToSyncModelView = Acad::ErrorStatus::eUnableToSyncModelView;
const Acad::ErrorStatus eUnableToTrimLastPiece = Acad::ErrorStatus::eUnableToTrimLastPiece;
const Acad::ErrorStatus eUnableToTrimSurface = Acad::ErrorStatus::eUnableToTrimSurface;
const Acad::ErrorStatus eUndefinedDxfGroupCode = Acad::ErrorStatus::eUndefinedDxfGroupCode;
const Acad::ErrorStatus eUndefinedLineType = Acad::ErrorStatus::eUndefinedLineType;
const Acad::ErrorStatus eUndefineShapeName = Acad::ErrorStatus::eUndefineShapeName;
const Acad::ErrorStatus eUndoNoGroupBegin = Acad::ErrorStatus::eUndoNoGroupBegin;
const Acad::ErrorStatus eUndoOperationNotAvailable = Acad::ErrorStatus::eUndoOperationNotAvailable;
const Acad::ErrorStatus eUnknownDxfFileFormat = Acad::ErrorStatus::eUnknownDxfFileFormat;
const Acad::ErrorStatus eUnknownHandle = Acad::ErrorStatus::eUnknownHandle;
const Acad::ErrorStatus eUnrecoverableErrors = Acad::ErrorStatus::eUnrecoverableErrors;
const Acad::ErrorStatus eUserBreak = Acad::ErrorStatus::eUserBreak;
const Acad::ErrorStatus eVertexAfterFace = Acad::ErrorStatus::eVertexAfterFace;
const Acad::ErrorStatus eVetoed = Acad::ErrorStatus::eVetoed;
const Acad::ErrorStatus eWasErased = Acad::ErrorStatus::eWasErased;
const Acad::ErrorStatus eWasNotErased = Acad::ErrorStatus::eWasNotErased;
const Acad::ErrorStatus eWasNotForwarding = Acad::ErrorStatus::eWasNotForwarding;
const Acad::ErrorStatus eWasNotifying = Acad::ErrorStatus::eWasNotifying;
const Acad::ErrorStatus eWasNotOpenForWrite = Acad::ErrorStatus::eWasNotOpenForWrite;
const Acad::ErrorStatus eWasOpenForNotify = Acad::ErrorStatus::eWasOpenForNotify;
const Acad::ErrorStatus eWasOpenForRead = Acad::ErrorStatus::eWasOpenForRead;
const Acad::ErrorStatus eWasOpenForUndo = Acad::ErrorStatus::eWasOpenForUndo;
const Acad::ErrorStatus eWasOpenForWrite = Acad::ErrorStatus::eWasOpenForWrite;
const Acad::ErrorStatus eWrongCellType = Acad::ErrorStatus::eWrongCellType;
const Acad::ErrorStatus eWrongDatabase = Acad::ErrorStatus::eWrongDatabase;
const Acad::ErrorStatus eWrongObjectType = Acad::ErrorStatus::eWrongObjectType;
const Acad::ErrorStatus eWrongSubentityType = Acad::ErrorStatus::eWrongSubentityType;
const Acad::ErrorStatus eXdataSizeExceeded = Acad::ErrorStatus::eXdataSizeExceeded;
const Acad::ErrorStatus eXRefDependent = Acad::ErrorStatus::eXRefDependent;
const Acad::ErrorStatus eXrefReloaded = Acad::ErrorStatus::eXrefReloaded;
const Acad::ErrorStatus eXrefReloadImpossibleAtThisTime = Acad::ErrorStatus::eXrefReloadImpossibleAtThisTime;
