/***************************************************************************
***
***     Copyright (C) 2022-2023 IntelliCAD Technology Consortium. All Rights Reserved.
***
***     Use of the information contained herein, in part or in whole,
***     in/as source code and/or in/as object code, in any way by anyone
***     other than authorized employees of The IntelliCAD Technology Consortium,
***     or by anyone to whom The IntelliCAD Technology Consortium  has not
***     granted use is illegal.
***
***     Description:
***
*****************************************************************************/
#pragma once

#pragma warning(disable : 4312)

#ifdef _FULLDEBUG_
#	define AC_FULL_DEBUG 1
#	pragma message("Warning! _FULLDEBUG_ is deprecated.")
#endif

#pragma comment(lib, "IcArxBridge.lib")
#pragma comment(lib, "IcArxAx.lib")
#pragma comment(lib, "IcArx.lib")
#pragma comment(lib, "IcArxGe.lib")
#pragma comment(lib, "IcArxUi.lib")
#ifdef AC_FULL_DEBUG
#	pragma comment(lib, "IcRxd.lib")
#else
#	pragma comment(lib, "IcRx.lib")
#endif

#include "acadstrc.h"
#include "acappvar.h"
#include "acarray.h"
#include "acdb.h"
#include "acdbabb.h"
#include "acdbads.h"
#include "AcDbClassIter.h"
#include "AcDbLMgr.h"
#include "acestext.h"
#include "AcField.h"
#include "acgi.h"
#include "AcGiLineAttributes.h"
#include "AcGiLineAttrUtils.h"
#include "acgimaterial.h"
#include "AcGiStyleAttributes.h"
#include "acgiutil.h"
#include "acgs.h"
#include "achapi.h"
#include "AcHeapOpers.h"
#include "acly.h"
#include "acmem.h"
#include "AcString.h"
#include "acsymutl.h"
#include "acut.h"
#include "acutads.h"
#include "acutil.h"
#include "acutmem.h"
#include "acutmigr.h"
#include "AdAChar.h"
#include "adesk.h"
#include "adeskabb.h"
#include "ads.h"
#include "adscodes.h"
#include "adsdef.h"
#include "adsmigr.h"
#include "appinfo.h"
#include "dbacis.h"
#include "dbAlignment.h"
#include "dbappgrip.h"
#include "dbapserv.h"
#include "dbaudita.h"
#include "dbbody.h"
#include "dbboiler.h"
#include "dbcfilrs.h"
#include "dbcolor.h"
#include "dbcurve.h"
#include "dbDataTable.h"
#include "dbdate.h"
#include "dbdict.h"
#include "dbdictdflt.h"
#include "dbDictUtil.h"
#include "dbdim.h"
#include "dbDimData.h"
#include "dbdynblk.h"
#include "dbelipse.h"
#include "dbents.h"
#include "dbeval.h"
#include "dbfcf.h"
#include "DbField.h"
#include "dbfiler.h"
#include "dbfilter.h"
#include "dbframe.h"
#include "dbgrip.h"
#include "dbgroup.h"
#include "dbhandle.h"
#include "dbhatch.h"
#include "dbid.h"
#include "dbidar.h"
#include "dbidmap.h"
#include "dbimage.h"
#include "dbindex.h"
#include "dbintar.h"
#include "dblaymgrrctr.h"
#include "dblayout.h"
#include "dblead.h"
#include "dblstate.h"
#include "dbmain.h"
#include "dbmaterial.h"
#include "dbmline.h"
#include "dbmstyle.h"
#include "dbmtext.h"
#include "dbobjptr.h"
#include "dbole.h"
#include "dbpl.h"
#include "dbplhldr.h"
#include "dbplotsettings.h"
#include "dbplotsetval.h"
#include "dbproxy.h"
#include "dbptrar.h"
#include "dbray.h"
#include "dbregion.h"
#include "dbsecurity.h"
#include "dbsol3d.h"
#include "dbspfilt.h"
#include "dbspindx.h"
#include "dbspline.h"
#include "dbsubeid.h"
#include "dbsymtb.h"
#include "dbsymutl.h"
#include "dbtable.h"
#include "dbTablestyle.h"
#include "dbtrans.h"
#include "dbxline.h"
#include "dbxrecrd.h"
#include "dbxutil.h"
#include "dblyfilt.h"
#include "dblyindx.h"
#include "dbxEntryPoint.h"
#include "drawable.h"
#include "geapln3d.h"
#include "gearc2d.h"
#include "gearc3d.h"
#include "geassign.h"
#include "geblok2d.h"
#include "geblok3d.h"
#include "gebndpln.h"
#include "gecbndry.h"
#include "gecint2d.h"
#include "gecint3d.h"
#include "geclip2d.h"
#include "gecomp2d.h"
#include "gecomp3d.h"
#include "gecone.h"
#include "gecsint.h"
#include "gecspl2d.h"
#include "gecspl3d.h"
#include "gecurv2d.h"
#include "gecurv3d.h"
#include "gecylndr.h"
#include "gedblar.h"
#include "gedll.h"
#include "gedwgio.h"
#include "gedxfio.h"
#include "geell2d.h"
#include "geell3d.h"
#include "geent2d.h"
#include "geent3d.h"
#include "geextc2d.h"
#include "geextc3d.h"
#include "geextsf.h"
#include "gefileio.h"
#include "gefiler.h"
#include "gegbl.h"
#include "gegblabb.h"
#include "gegblge.h"
#include "gegblnew.h"
#include "geintarr.h"
#include "geintrvl.h"
#include "gekvec.h"
#include "gelent2d.h"
#include "gelent3d.h"
#include "gelibver.h"
#include "geline2d.h"
#include "geline3d.h"
#include "gelnsg2d.h"
#include "gelnsg3d.h"
#include "gemat2d.h"
#include "gemat3d.h"
#include "genurb2d.h"
#include "genurb3d.h"
#include "genurbsf.h"
#include "geoffc2d.h"
#include "geoffc3d.h"
#include "geoffsf.h"
#include "gepent2d.h"
#include "gepent3d.h"
#include "geplanar.h"
#include "geplane.h"
#include "geplin2d.h"
#include "geplin3d.h"
#include "gepnt2d.h"
#include "gepnt3d.h"
#include "geponc2d.h"
#include "geponc3d.h"
#include "geponsrf.h"
#include "gepos2d.h"
#include "gepos3d.h"
#include "gept2dar.h"
#include "gept3dar.h"
#include "geray2d.h"
#include "geray3d.h"
#include "gescl2d.h"
#include "gescl3d.h"
#include "gesent2d.h"
#include "gesent3d.h"
#include "gesphere.h"
#include "gessint.h"
#include "gesurf.h"
#include "getol.h"
#include "getorus.h"
#include "gevc2dar.h"
#include "gevc3dar.h"
#include "gevec2d.h"
#include "gevec3d.h"
#include "gevptar.h"
#include "gexbndsf.h"
#include "graph.h"
#include "idgraph.h"
#include "imgdef.h"
#include "imgent.h"
#include "imgvars.h"
#include "inetstrc.h"
#include "linetypeengine.h"
#include "migrtion.h"
#include "rxboiler.h"
#include "rxclass.h"
#include "rxdefs.h"
#include "rxdict.h"
#include "rxditer.h"
#include "rxdlinkr.h"
#include "rxevent.h"
#include "rxiter.h"
#include "rxkernel.h"
#include "rxnames.h"
#include "rxobject.h"
#include "rxprotevnt.h"
#include "rxregsvc.h"
#include "rxsrvice.h"
#include "sorttab.h"
#include "summinfo.h"
#include "textengine.h"
#include "xgraph.h"
#include "xreflock.h"

#include "PAL/api/codepgid.h"

#ifdef __ATLCOM_H__
#	ifndef _ACRXAPP
#		include "axdb.h"
#	else
#		include "acadi.h"
#	endif	// _ACRXAPP
#	include "acpexctl.h"
#	include "acpi.h"
#	include "AcPp.h"
#	include "axboiler.h"
#	include "axlock.h"
#	include "axmat3d.h"
#	include "axobjref.h"
#	include "axpnt2d.h"
#	include "axpnt3d.h"
#	include "axtempl.h"
#	include "category.h"
#	include "dynprops.h"
#	include "oleaprot.h"
#	include "opmdialog.h"
#	include "opmdrvr.h"
#	include "opmext.h"
#	include "opmimp.h"
#endif	// __ATLCOM_H__

#ifdef _DBX_HOST_APPLICATION_
#	include "AcDbXref.h"
#	include "dbhaext.h"
#	include "truetypetext.h"
#endif	// _DBX_HOST_APPLICATION_

#ifdef _BREP_SUPPORT_
#	include "brbctrav.h"
#	include "brbetrav.h"
#	include "brbftrav.h"
#	include "brbrep.h"
#	include "brbstrav.h"
#	include "brbvtrav.h"
#	include "brcplx.h"
#	include "brcstrav.h"
#	include "bredge.h"
#	include "brelem.h"
#	include "brelem2d.h"
#	include "breltrav.h"
#	include "brent.h"
#	include "brentrav.h"
#	include "brface.h"
#	include "brfltrav.h"
#	include "brgbl.h"
#	include "brhit.h"
#	include "brletrav.h"
#	include "brloop.h"
#	include "brlvtrav.h"
#	include "brm2dctl.h"
#	include "brmctl.h"
#	include "brment.h"
#	include "brmesh.h"
#	include "brmesh2d.h"
#	include "brmetrav.h"
#	include "brnode.h"
#	include "brprops.h"
#	include "brsftrav.h"
#	include "brshell.h"
#	include "brtrav.h"
#	include "brvetrav.h"
#	include "brvltrav.h"
#	include "brvtx.h"
#endif	// _BREP_SUPPORT_
