/***************************************************************************
***
***     Copyright (C) 2022-2023 IntelliCAD Technology Consortium. All Rights Reserved.
***
***     Use of the information contained herein, in part or in whole,
***     in/as source code and/or in/as object code, in any way by anyone
***     other than authorized employees of The IntelliCAD Technology Consortium,
***     or by anyone to whom The IntelliCAD Technology Consortium  has not
***     granted use is illegal.
***
***     Description: Various enums
***
*****************************************************************************/
typedef [uuid(37819C79-E6D2-44C0-823F-AA936C4DA2E8)] [v1_enum] enum dcContentMode
{
    dcDesktop		     = 0,
    dcOpenDrawings	     = 1,
    dcCustomContent	     = 2,
} dcContentMode;

typedef [uuid(C2841C14-F090-452D-83C1-73D09DF8863E)] [v1_enum] enum dcFinderCommands
{
	dcFinderCmdInsert           = 1,
	dcFinderCmdAttachAsXref     = 2,
	dcFinderCmdCopy             = 3,
	dcFinderCmdOpen             = 4,
	dcFinderCmdLoad             = 5,
	dcFinderCmdFirst            = 1,
	dcFinderCmdCustFirst        = 6,
	dcFinderCmdCustLast         = 32,
	dcFinderCmdLast             = 32,
} dcFinderCommands;

typedef [uuid(F0ED2B88-E2AB-4AD4-9D86-60208DE19797)] [v1_enum] enum dcFinderObjectTypes
{
	dcFinderADeskDrawing        = 0,
	dcFinderADeskBlock          = 1,
	dcFinderADeskLayer          = 2,
	dcFinderADeskActrix         = 3,
	dcFinderADeskActrixCatalog  = 4,
	dcFinderADeskXref           = 5,
	dcFinderADeskLinetypes      = 6,
	dcFinderThirdParty          = 7,
	dcFinderADeskLayouts        = 8,
	dcFinderADeskDimStyles      = 9,
	dcFinderADeskTextStyles     = 10,
	dcFinderADeskTableStyles    = 11,
    dcFinderADeskMultileaderStyles = 12,
    dcFinderADeskVisualStyles   = 13,
    dcFinderADeskSectionViewStyles = 14,
    dcFinderADeskDetailViewStyles = 15,
} dcFinderObjectTypes;

typedef [uuid(DEB204B8-245D-48A8-B2CB-139A6637787D)] [v1_enum] enum dcFinderTypeMask
{
    dcFinderTypeMaskDate            = 1,
    dcFinderTypeMaskAdvanced        = 2,
    dcFinderTypeMaskFileBased       = 4,
    dcFinderTypeMaskDateReturned    = 8,
    dcFinderTypeMaskSizeReturned    = 16,
} dcFinderTypeMask;

typedef [uuid(8DFB7746-AADA-4214-BEA6-733D0F7A7CBA)] [v1_enum] enum dcItemDataSource
{
    dcIDSNavigator      = 0,
    dcIDSPalette        = 1,
} dcItemDataSource;

typedef [uuid(E3B40DC7-EFF2-49DD-B502-A39427064644)] [v1_enum] enum dcMenuInfoFlag
{
    dcHelpText          = 0,
    dcValidate          = 1,
    dcVerb              = 2,
} dcMenuInfoFlag;

typedef [uuid(682FF216-9606-4638-B689-BB68826051EC)] [v1_enum] enum dcNavNodeRelation
{
    dcNavNodeFirst = 0,
    dcNavNodeLast,
    dcNavNodeSort,
} dcNavNodeRelation;

typedef [uuid(6C3D806F-7A3A-431D-AD8F-BD392B4C2CE1)] [v1_enum] enum dcPalColAlignment
{
    dcPalColLeft    = 0,
    dcPalColRight   = 1,
    dcPalColCenter  = 2
} dcPalColAlignment;

typedef [uuid(E2FF5E2C-A414-4EB7-8808-09DD2C2958EB)] [v1_enum] enum dcPalSortOrder
{
    dcPalAscending  = 0,
    dcPalDescending = 1
} dcPalSortOrder;

typedef [uuid(19C1C8A1-3E0A-4F99-A84F-6494015A0B6D)] [v1_enum] enum dcPalViewType
{
    dcPalIcon       = 0,
    dcPalSmallIcon  = 1,
    dcPalList       = 2,
    dcPalReport     = 3
} dcPalViewType;

typedef [uuid(6B23EF43-4110-4DA3-B690-89013A66B34A)] [v1_enum] enum dcPane
{
    dcPreview            = 0,
    dcDescription        = 1,
    dcNavigator          = 2,
} dcPane;

